FROM node:lts

# npm のキャッシュ場所を固定
ENV NPM_CONFIG_CACHE=/npm-cache

# create-expo-app を入れる
RUN npm install -g create-expo-app

# 一度だけテンプレを作って依存を解決→npm キャッシュに格納
RUN npx create-expo-app /_seed \
    && cd / && rm -rf /_seed

WORKDIR /workspace
